#!/usr/bin/env ruby
require "rubygems"
require "bundler/setup"

Bundler.require :gem_default, :gem_development

if File.exists?(file = File.expand_path('../../.credentials', __FILE__))
  BettyResource.configure MultiJson.decode(File.read(file))
end

if File.exists?(file = File.expand_path('../../credentials.yaml', __FILE__))
  BettyResource.configure YAML.load_file(file)
end

puts "Loading BettyResource development environment (#{BettyResource::VERSION})"
puts "Configured connection with #{BettyResource.config.host}".yellow
Pry.start