#!/usr/bin/env ruby
require "rubygems"
require "bundler/setup"

Bundler.require :gem_default

BettyResource.configure(MultiJson.decode(File.read(File.expand_path('../../.credentials', __FILE__))))

puts "Loading BettyResource development environment (#{BettyResource::VERSION})"
puts "Configured connection with #{BettyResource.config.host}".yellow
Pry.start